<?php echo $this->doctype(); ?>

<html lang="fr" ng-app="myTennisPal">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <script type="application/javascript" src="/js/vendor/angular.min.js"></script>
        <script type="application/javascript" src="/js/vendor/angular-route.min.js"></script>
        <script type="application/javascript" src="/js/vendor/jquery.min.js"></script>
        <script type="application/javascript" src="/js/vendor/bootstrap.min.js"></script>
        <script type="application/javascript" src="https://maps.googleapis.com/maps/api/js?v=3.17"></script>

        <!--[if lt IE 9]><script type="text/javascript" src="/js/vendor/html5shiv.js"></script><![endif]-->
        <!--[if lt IE 9]><script type="text/javascript" src="/js/vendor/respond.min.js"></script><![endif]-->

        <script type="text/javascript" src="/js/src/ng/app.js"></script>
        <script type="text/javascript" src="/js/src/ng/controller/index.js"></script>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Skeleton Application') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="content">
            <?php echo $this->content; ?>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
