<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?v=3.17"></script>
<script type="application/javascript">

	function getNavigatorGeolocation(onSuccess, onError) {
		if (navigator.geolocation) {
			navigator.geolocation.getCurrentPosition(function(position) {
				onSuccess(position.coords.latitude, position.coords.longitude);
			}, onError);
		} else {
			onError();
		}
	}

	function requestDepartmentMarkers(onSuccess) {
		$.get('/api/department-marker').success(onSuccess).error(console.error);
	}

	function initMap(lat, lng) {
		var map = new google.maps.Map(document.getElementById('map'), {
			zoom: 6,
			center: new google.maps.LatLng(lat, lng)
		});

		requestDepartmentMarkers(function(res) {
			var markersData = res._embedded.department_marker;

			markersData.forEach(function(markerData) {
				var marker = new google.maps.Marker({
					title: markerData.title,
					position: new google.maps.LatLng(markerData.latitude, markerData.longitude),
					map: map
				});
			});
		});
	}

	google.maps.event.addDomListener(window, 'load', function() {
		getNavigatorGeolocation(function(lat, lng) {
			initMap(lat, lng);
		}, function() {
			initMap(43.142859, 5.937183);
		});
	});

</script>

<div class="map-canvas">
	<div id="map" style="width: 100%; height: 100%;"></div>
</div>
