<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?v=3.17"></script>
<script type="application/javascript">

	function getNavigatorGeolocation(onSuccess, onError) {
		if (navigator.geolocation) {
			navigator.geolocation.getCurrentPosition(function(position) {
				onSuccess(position.coords.latitude, position.coords.longitude);
			}, onError);
		} else {
			onError();
		}
	}

	function initMap(lat, lng) {
		var map = new google.maps.Map(document.getElementById('map'), {
			zoom: 14,
			center: new google.maps.LatLng(lat, lng)
		});
	}

	google.maps.event.addDomListener(window, 'load', function() {
		getNavigatorGeolocation(function(lat, lng) {
			initMap(lat, lng);
		}, function() {
			initMap(43.142859, 5.937183);
		});
	});

</script>

<div id="map" style="width: 100%; height: 600px;"></div>